CREATE TABLE EMPLOYEES (
EMP_NO INT PRIMARY KEY,
EMP_DOB DATE NOT NULL,
EMP_FNAME VARCHAR(15) NOT NULL,
EMP_LNAME VARCHAR(15) NOT NULL,
SEX ENUM('M','F'),
EMP_HIRE_DATE DATE NOT NULL);


CREATE TABLE TITLES(
TITLE VARCHAR(50) NOT NULL PRIMARY KEY,
FROM_DATA DATE NOT NULL,
TO_DATE DATE NOT NULL,
EMP_NO INT,
INDEX (EMP_NO),
CONSTRAINT FK_TITLE_ORG FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO));



CREATE TABLE SALARIES(
EMP_NO INT,
SALARY INT NOT NULL,
FROM_DATE DATE NOT NULL,
TO_DATE DATE NOT NULL,
INDEX (EMP_NO),
CONSTRAINT PK_SALARIES PRIMARY KEY (FROM_DATE, TO_DATE),
CONSTRAINT FK_SALARIES_ORG FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO));


CREATE TABLE DEPARTMENTS(
DEPT_NO CHAR(4) NOT NULL PRIMARY KEY,
DEPT_NAME VARCHAR(40) NOT NULL);



CREATE TABLE DEPT_EMP(
EMP_NO INT,
DEPT_NO CHAR(4) NOT NULL,
FROM_DATE DATE NOT NULL,
TO_DATE DATE NOT NULL,
INDEX (EMP_NO),
INDEX (DEPT_NO),
PRIMARY KEY (EMP_NO,DEPT_NO),
CONSTRAINT FK_DEPT_EMP_ORG FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
CONSTRAINT FK_DEPT_MAN_ORG FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO));


CREATE TABLE DEPT_MAN(
DEPT_NO      CHAR(4)         NOT NULL,
EMP_NO     INT,             
FROM_DATE DATE NOT NULL,
TO_DATE DATE NOT NULL,
INDEX (EMP_NO),
INDEX (DEPT_NO),
PRIMARY KEY (EMP_NO,DEPT_NO),
CONSTRAINT FK_DEPT_MANG_ORG FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
CONSTRAINT FK_DEPT_MANAG_ORG FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO));

//ALTER TABLE DEPT_MANAGER ADD CONSTRAINT FK_DEPT_MANG_ORG FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO));


